import { Wagmi } from '../provider/wagmi-provider';
import { QueryProvider } from '../provider/query-provider';
import './global.css';
export const metadata = {
  title: 'Welcome to virtuperks-ui',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Wagmi>
          <QueryProvider>{children}</QueryProvider>
        </Wagmi>
      </body>
    </html>
  );
}
